<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<title></title>
	</head>
	<body>
		<b>Booking Request</b>
		<ul>
			<li><b>Artist:</b> <?= $booking->artist->name ?></li>
			<li><b>Firstname:</b> <?= $booking->firstname ?></li>
			<li><b>Lastname:</b> <?= $booking->lastname ?></li>
			<li><b>Company:</b> <?= $booking->company ?></li>
			<li><b>E-Mail:</b> <?= $booking->email ?></li>
			<li><b>Location:</b> <?= $booking->location ?></li>
			<li><b>Size:</b> <?= $booking->size ?></li>
			<li><b>Date:</b> <?= $booking->date ?></li>
			<li><b>Message:</b> <?= $booking->message ?></li>
		</ul>
	</body>
</html>
