<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<title></title>
	</head>
	<body>
		Welcome to the 3886records mailinglist<br/>
		<br/>
		You can manage your subscription here:<br/>
		<a href="http://www.3886records.de/subscriptions/manage/<?= $subscription->hash ?>">http://www.3886records.de/subscriptions/manage/<?= $subscription->hash ?></a>
		<br/>
		<br/>
		<br/>
		<a href="http://www.3886records.de">www.3886records.de</a>
	</body>
</html>
