<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<title></title>
	</head>
	<body>
		Thank you for your interest in 3886records.<br/>
		You receive this because you have entered your email address in our mailinglist.<br/>
		If you did not request the subscription just ignore this mail.<br/>
		<br/>
		To confirm your subscription click the following link:<br/>
		<a href="http://www.3886records.de/subscriptions/activate/<?= $subscription->hash ?>">http://www.3886records.de/subscriptions/confirm/<?= $subscription->hash ?></a>
		<br/>
		<br/>
		<br/>
		<a href="http://www.3886records.de">www.3886records.de</a>
	</body>
</html>
