<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <div class="hero-unit">
        <h1><?= $artist->name ?></h1>
        <p style="font-weight: bold; margin-bottom: 20px;"><?= $artist->shortInfo ?></p>
		<div class="span3">
			<ul class="thumbnails">
				<li>
					<div class="thumbnail">
						<img width="200" height="200" src="/img/artists/<?= $artist->key ?>.jpg" alt="<?= $artist->name ?>" />
					</div>
				</li>
			</ul>
		</div>
		<div class="span7" style="float: left">	
			<p><?= $artist->longInfo ?></p>
		</div>
		<? if (count($artist->links)): ?>
			<ul class="social" style="width: 34px; float: right;">
			<? foreach ($artist->links as $link): ?>
				<li><a target="_blank" href="<?= $link->link ?>"><img alt="<?= ucfirst($link->type) ?>" title="<?= ucfirst($link->type) ?>" src="/img/social/<?= $link->type ?>.png" border="0" /></a></li>
			<? endforeach ?>
			</ul>
		<? endif ?>
		<div class="clear"></div>
    </div>
</div>
<? if (count($artist->events)): ?>
	<div class="container events-small">
		<h2>Upcomming Events with <?= $artist->name ?></h2>
		<ul class="thumbnails">
			<? foreach ($artist->events as $event): ?>
				<li class="span2">
					<div class="thumbnail">
						<? if (!empty($event->facebook)): ?>
							<br/><a target="_blank" title="Event on Facebook" href="<?= $event->facebook ?>">
						<? endif ?>
						<img width="100" src="/img/events/<?= $event->flyer ?>" border="0" alt="<?= $event->name ?>" title="<?= $event->name ?>"
						<? if (!empty($event->facebook)): ?>
							</a>
						<? endif ?>
					</div>
				</li>
			<? endforeach ?>
		</ul>
	</div>
<? endif ?>
<? if (count($artist->videos)): ?>
	<div class="container videos">
		<h2>Videos</h2>
		<ul class="thumbnails with-border">
			<? foreach ($artist->videos as $video): ?>
				<li class="span6">
					<div class="thumbnail">
						<iframe style="margin-left: auto; margin-right: auto;" width="100%" height="360" src="<?= $video->link ?>" frameborder="0" allowfullscreen></iframe>
					</div>
				</li>
			<? endforeach ?>
		</ul>
	</div>
<? endif ?>
<? if (!empty($artist->soundcloud)): ?>
	<div class="container">
		<? if ($artist->type == \Models\Artist::TYPE_DJ): ?>
			<h2>DJ-Sets</h2>
		<? else: ?>
			<h2>Tracks</h2>
		<? endif ?>
		<iframe width="100%" height="450" scrolling="no" frameborder="no" src="<?= $artist->soundcloud ?><?= DataProvider::getInstance()->getSoundcloudParams() ?>"></iframe>
	</div>
<? endif ?>
<? if (!empty($artist->mixcloud)): ?>
	<div class="container">
		<h2>DJ-Sets</h2>
		<?= $artist->mixcloud ?>
	</div>
<? endif ?>
