<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <div class="hero-unit">
        <h1>Artist overview</h1>
    </div>
	<div style="height:20px;"></div>
	<ul class="thumbnails">
		<? foreach ($artists as $artist): ?>
	    <li class="span4">
			<div class="thumbnail">
				<a href="/artist/<?= $artist->key ?>" data-method="async">
					<h3><?= $artist->name ?></h3>
					<img style="width: 200px; height: 200px;" src="/img/artists/<?= $artist->key ?>.jpg" alt="<?= $artist->name ?>">
				</a>
			</div>
		</li>
		<? endforeach ?>
	</ul>
</div>
