<?= ViewLoader::load('breadcrumb', array('items' => array((object)array('active' => true, 'title' => 'Home'), (object)array('title' => 'Contest')))) ?>
<div class="container">
    <div class="hero-unit">
        <h1><span class="raleway">Psy&Prog</span>.Contest</h1>
        <p><strong>Take the chance to get your track published on all major online platforms!</strong></p>
    </div>
	
	<div class="hero-unit">
		<h4>How to participate?</h4>
		<ul class="light">
			<li>Upload your track on Soundcloud</li>
			<li>Add it to <a target="_blank" href="//soundcloud.com/groups/3886records-prog-psy-goa-contest">this Soundcloud group</a></li>
			<li>Wait for approval</li>
		</ul>
		
		<h4>The rules</h4>
		<ul class="light">
			<li>The genre must be Progressive Trance, Psytrance, Goatrance or a mix of them</li>
			<li>The track must be uploaded until December 31th 2013</li>
			<li>The track must not be released or signed by another label</li>
			<li>The Track must be an original (no remixes)</li>
			<li>The artist must hold all rights on the track and not violate the rights of any third person</li>
		</ul>
		<br/>
		
		<h4>Deadline</h4>
		<ul class="light">
			<li>December 31st 2013. Be sure to submit your finished Track until the end of the year!</li>
		</ul>
		<br/>

		<h4>The prize</h4>
		<ul class="light">
			<li>The winning track(s) will be released via 3886records. Good luck!</li>
		</ul>		
	</div>
</div>