<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>

<? if (isset($events->upcomming) && is_array($events->upcomming)): ?>
	<div class="container events eventsfull">
		<h2>Upcomming Events</h2>
		<ul class="thumbnails">
			<? foreach ($events->upcomming as $event): ?>
				<li class="span4">
					<div class="thumbnail">
						<h4><?= $event->name ?></h4>
						<span class="location"><?= $event->shortInfo ?></span><br/>
						<span class="date"><?= $event->fromTime ?></span>
						<? if (isset($event->facebook)): ?>
							<br/><a title="Event on Facebook" href="<?= $event->facebook ?>" target="_blank">
						<? endif ?>
						<img border="0" src="/img/events/<?= $event->flyer ?>" border="0" alt="<?= $event->name ?>" title="<?= $event->name ?>" />
						<? if (isset($event->facebook)): ?>
							</a>
						<? endif ?>
						<? if (isset($event->artists) && is_array($event->artists)): ?>
							<div class="acts">
							<? foreach ($event->artists as $artist): ?>
								<a data-method="async" href="/artist/<?= $artist->key ?>"><?= $artist->name ?></a>: <?= $artist->shortInfo ?><br/>
							<? endforeach ?>
							</div>
						<? endif ?>
					</div>
				</li>
			<? endforeach ?>
		</ul>
	</div>
<? endif ?>

<? if (isset($events->past) && is_array($events->past)): ?>
	<div class="container events eventsfull">
		<h2>Past Events</h2>
		<ul class="thumbnails">
			<? foreach ($events->past as $event): ?>
				<li class="span4">
					<div class="thumbnail">
						<h4><?= $event->name ?></h4>
						<span class="location"><?= $event->shortInfo ?></span><br/>
						<span class="date"><?= $event->fromTime ?></span>
						<? if (isset($event->facebook)): ?>
							<br/><a title="Event on Facebook" href="<?= $event->facebook ?>" target="_blank">
						<? endif ?>
						<img border="0" src="/img/events/<?= $event->flyer ?>" border="0" alt="<?= $event->name ?>" title="<?= $event->name ?>" />
						<? if (isset($event->facebook)): ?>
							</a>
						<? endif ?>
						<? if (isset($event->artists) && is_array($event->artists)): ?>
							<div class="acts">
							<? foreach ($event->artists as $artist): ?>
								<a href="/artist/<?= $artist->key ?>"><?= $artist->name ?></a>: <?= $artist->shortInfo ?><br/>
							<? endforeach ?>
							</div>
						<? endif ?>
					</div>
				</li>
			<? endforeach ?>
		</ul>
	</div>
<? endif ?>