<? if (!isset($galleryId) || empty($galleryId)) $galleryId = 341782652670884 ?>	
<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <div class="hero-unit">
        <h1>Party Gallery</h1>
        <p style="font-weight: bold; margin-bottom: 20px;">
        	<a data-method="async" href="/pics/341782652670884">Wings of Garuda</a>
        	|
        	<a data-method="async" href="/pics/333230870192729">Mahadeva Linga</a>
        	|
        	<a data-method="async"href="/pics/283757605140056">3886 in Love</a>
        	|
        	<a data-method="async" href="/pics/279147742267709">Herrnesium</a>
        	|
        	<a data-method="async" href="/pics/264519910397159">Corpus Sarasvati</a>
        	|
        	<a data-method="async" href="/pics/262385800610570">Lustig Stampfen</a>
        	|
        	<a data-method="async" href="/pics/209551022560715">Labelnight</a>
        </p>
		<div class="span12" id="photos"></div>
		<iframe src="http://embedsocial.com/facebook_album/album_photos/<?= $galleryId ?>" width="100%" height="1450" frameborder="0" scrolling="no" marginheight="0"  marginwidth="0"></iframe>
	</div>
</div>
		
