<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <div class="hero-unit">
        <h1><?= $genre->name ?></h1>
        <p><?= $genre->shortInfo ?></p>
		<? if (isset($genre->longInfo)): ?>
			<p><?= $genre->longInfo ?></p>
		<? endif ?>
    </div>
</div>
<? if (isset($genre->soundcloud)): ?>
	<div class="container">
		<h2>Tracks</h2>
		<iframe width="100%" height="700" scrolling="no" frameborder="no" src="<?= $genre->soundcloud ?><?= DataProvider::getInstance()->getSoundcloudParams() ?>"></iframe>
	</div>
<? endif ?>
