<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <div class="hero-unit">
        <h1><?= $label->name ?></h1>
        <p style="font-weight: bold; margin-bottom: 20px;"><?= $label->shortInfo ?></p>
		<div class="span3">
			<ul class="thumbnails">
				<li>
					<div class="thumbnail">
						<img src="/img/labels/<?= $label->key ?>.png" alt="<?= $label->name ?>" />
					</div>
				</li>
			</ul>
		</div>
		<? if (isset($label->longInfo)): ?>
			<div class="span7">
				<p><?= $label->longInfo ?></p>
			</div>
		<? endif ?>
		<? if (isset($label->links)): ?>
			<ul class="social">
			<? foreach ($label->links as $type => $link): ?>
				<li><a target="_blank" href="<?= $link ?>"><img alt="<?= ucfirst($type) ?>" title="<?= ucfirst($type) ?>" src="/img/social/<?= $type ?>.png" border="0" /></a></li>
			<? endforeach ?>
			</ul>
		<? endif ?>
		<div class="clear"></div>
    </div>
</div>

<? if (isset($label->soundcloud)): ?>
	<div class="container">
		<h2>Tracks</h2>
		<iframe width="100%" height="450" scrolling="no" frameborder="no" src="<?= $label->soundcloud ?><?= DataProvider::getInstance()->getSoundcloudParams(true) ?>"></iframe>
	</div>
<? endif ?>

<? if (isset($label->address) || isset($label->phone) || isset($label->email)): ?>
<div class="container">
	<h2>Contact</h2>
	<div class="span12 first backgrounded">
		<? if (isset($label->email)): ?>
			<p><strong>E-Mail:</strong> <?= $label->email ?></p>
		<? endif ?>
		<? if (isset($label->phone)): ?>
			<p><strong>Phone:</strong> <?= $label->phone ?></p>
		<? endif ?>
		<? if (isset($label->address)): ?>
			<p>
				<strong>Address:</strong><br/>
				<?= $label->address ?>
			</p>
		<? endif ?>
	</div>
</div>
<? endif ?>