<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <div class="hero-unit">
        <h1><?= $label->name ?></h1>
        <p style="font-weight: bold; margin-bottom: 20px;"><?= $label->shortInfo ?></p>
		<div class="span3">
			<ul class="thumbnails">
				<li>
					<div class="thumbnail">
						<img src="/img/labels/<?= $label->key ?>.png" alt="<?= $label->name ?>" />
					</div>
				</li>
			</ul>
		</div>
		<? if (isset($label->longInfo)): ?>
			<div class="span7">
				<p><?= $label->longInfo ?></p>
			</div>
		<? endif ?>
		<? if (isset($label->links)): ?>
			<ul class="social">
			<? foreach ($label->links as $link): ?>
				<li><a target="_blank" href="<?= $link->link ?>"><img alt="<?= ucfirst($link->type) ?>" title="<?= ucfirst($link->type) ?>" src="/img/social/<?= $link->type ?>.png" border="0" /></a></li>
			<? endforeach ?>
			</ul>
		<? endif ?>
		<div class="clear"></div>
    </div>
</div>

<? if (isset($label->soundcloud)): ?>
	<div class="container">
		<h2>Tracks</h2>
		<iframe width="100%" height="450" scrolling="no" frameborder="no" src="<?= $label->soundcloud ?><?= DataProvider::getInstance()->getSoundcloudParams(true) ?>"></iframe>
	</div>
<? endif ?>
