<ul class="nav pull-right">

  <li class="dropdown"><a data-method="async" href="/pics"><span><i class="icon-film"></i></span> Gallery</b></a></li>  
  <li class="divider-vertical"></li>
  
  <li><a href="/events" data-method="async"><span><i class="icon-calendar"></i></span> Events</a></li>
  <li class="divider-vertical"></li>
  
  <?php /*
  <li class="divider-vertical"></li>
  <li class="dropdown"><a href="/artists" class="dropdown-toggle" data-toggle="dropdown"><span class="current"><i class="icon-signal"></i></span> Releases <b class="caret"></b></a>
    <ul class="dropdown-menu">
		<li><a data-method="async" href="/releases/upcoming">Upcoming Releases</a></li>
		<li><a data-method="async" href="/releases/latest">Latest Releases</a></li>
    </ul>
  </li>
  <li class="divider-vertical"></li>
  */ ?>

  <li class="dropdown"><a href="/artists" class="dropdown-toggle" data-toggle="dropdown"><span><i class="icon-star"></i></span> Artists <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a data-method="async" href="/artists">Artist overview</a></li>
      <li class="divider"></li>
    <? foreach ($artists as $artist): ?>
    <li><a data-method="async" href="/artist/<?= $artist->key ?>"><?= $artist->name ?></a></li>
    <? endforeach ?>
    </ul>
  </li>
  <li class="divider-vertical"></li>

  <li class="dropdown"><a href="/djs" class="dropdown-toggle" data-toggle="dropdown"><span><i class="icon-play-circle"></i></span> DJs <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a data-method="async" href="/djs">DJ overview</a></li>
      <li class="divider"></li>
    <? foreach ($djs as $dj): ?>
    <li><a data-method="async" href="/dj/<?= $dj->key ?>"><?= $dj->name ?></a></li>
    <? endforeach ?>
    </ul>
  </li>


  
  <li class="divider-vertical"></li>
  <li class="dropdown"><a data-method="async" href="/genres"><span><i class="icon-music"></i></span> Genres</b></a>
    <!--<ul class="dropdown-menu">
	  <? foreach ($genres as $genre): ?>
		<li><a data-method="async" href="/genre/<?= $genre->key ?>"><?= $genre->name ?></a></li>
	  <? endforeach ?>
    </ul>
    -->
  </li>

  <li class="divider-vertical"></li>

  <? if (null === $user): ?>
    <li><a href="/login" data-method="async"><span><i class="icon-user"></i></span> Login</a></li>
  <? else: ?>
    <li class="dropdown"><a href="/profile" class="dropdown-toggle" data-toggle="dropdown"><span><i class="icon-user"></i></span> Profile <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a data-method="async" href="/profile">My profile</a></li>
        <li><a href="/logout">Logout</a></li>
      </ul>
    </li>
  <? endif ?>

  <?/*
  <li class="divider-vertical"></li>
  <li class="dropdown"><a href="/artists" class="dropdown-toggle" data-toggle="dropdown"><span class="current"><i class="icon-headphones"></i></span> Labels <b class="caret"></b></a>
    <ul class="dropdown-menu">
	  <? foreach ($labels as $label): ?>
		<li><a data-method="async" href="/label/<?= $label->key ?>"><?= $label->name ?></a></li>
	  <? endforeach ?>
    </ul>
  </li>
  */?>

</ul>
