<ul class="nav pull-right">
  <li>
    <a data-method="async" href="/home"><span class="current"><i class="icon-home"></i></span> Home</a>
  </li>
  <li class="divider-vertical"></li>
  <li class="dropdown"><a href="/artists" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-music"></i> Artists <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a data-method="async" href="/artists">Artist overview</a></li>
      <li class="divider"></li>
      <li><a data-method="async" href="/artist/aljoshakonstanty">Aljosha Konstanty</a></li>
      <li><a data-method="async" href="/artist/darwinxp">Darwin Experience</a></li>
      <li><a data-method="async" href="/artist/euphoristix">Euphoristix</a></li>
      <li><a data-method="async" href="/artist/sherwee">Sherwee</a></li>
      <li><a data-method="async" href="/artist/shinson">Shinson</a></li>
      <li><a data-method="async" href="/artist/spekta">Spekta</a></li>
      <li><a data-method="async" href="/artist/stormanimal">StormAnimal</a></li>
    </ul>
  </li>
</ul>
