<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <div class="jumbotron hero-unit">
        <div>
            <h1>3886profile</h1>
        </div>
		<p>
			All information on your 3886records account.
		</p>
		<p>
			<? if (isset($artist)): ?>
				<strong>Hello <?= $artist->name ?>!</strong>
			<? endif ?>
		</p>
		<p><i>coming sooon...</i></p>
    </div>
</div>