<link rel="stylesheet" type="text/css" media="screen" href="/css/cassette-tape-ui.css" />

<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <div class="hero-unit">
        <h1><?= $title ?></h1>
    </div>
</div>
<div class="container">
	<div class="row-fluid">
		<div class="span12">


			<!-- begin tape -->
			<div class="clear ma-r90 cutout tape" data-url="/promotions/spekta_cool_air_preview.mp3">
			 <div class="blur-image-wrapper">
			  <canvas class="blur-image"></canvas>
			 </div>
			 <div class="transparency-sheet"></div>
			 <div class="tape-shell image-mask" data-image-repeat="true" data-mask-url="/img/ma-r90-mask.png"></div>
			 <div class="tape-gradient image-mask" data-mask-url="/img/ma-r90-mask.png"></div>
			 <div class="tab-left">
			  <div class="notch"></div>
			  <div class="ridge"></div>
			 </div>
			 <div class="tab-right">
			  <div class="notch"></div>
			  <div class="ridge"></div>
			 </div>
			 <div class="rail-left"></div>
			 <div class="rail-right"></div>
			 <div class="rail-middle">
			  <div class="rail-middle-outline">
			   <div class="tape-pad-holder">
			    <div class="tape-pad"></div>
			    <div class="tape-pad-line"></div>
			   </div>
			  </div>
			  <div class="screw-bm"></div>
			 </div>
			 <div class="screw-tl"></div>
			 <div class="screw-tr"></div>
			 <div class="screw-bl"></div>
			 <div class="screw-br"></div>
			 <div class="screw-tm"></div>
			 <div class="left reel-mask"></div>
			 <div class="right reel-mask"></div>
			 <canvas class="connecting-tape"></canvas>
			 <div class="left reel"></div>
			 <div class="left spokes"></div>
			 <div class="right reel"></div>
			 <div class="right spokes"></div>
			 <div class="progress-notches">
			  <div class="n1"></div>
			  <div class="n2"></div>
			  <div class="n3"></div>
			  <div class="n4"></div>
			  <div class="n5"></div>
			  <div class="n6"></div>
			  <div class="n7"></div>
			  <div class="n8"></div>
			  <div class="n9"></div>
			 </div>
			 <div class="label">Spekta - Cool Air (preview 2013)</div>
			 <div class="aqua controls">
			  <div class="bd">
			   <ul>
			    <li><a href="#" title="play/pause" class="play">&#9658;</a></li>
			    <li><a href="#" title="rewind" class="rew">&#171;</a></li>
			    <li><a href="#" title="fast-forward" class="ffwd">&#187;</a></li>
			    <li><a href="#" title="stop" class="stop">&#9632;</a></li>
			   </ul>
			  </div>
			 </div>
			</div>
			<!-- end tape -->

			<!-- begin tape -->
			<div class="clear blue ma-r90 cutout tape" data-url="/promotions/La_Boom_-_Selbstmord_ist_kein_Auxweg.mp3" style="margin-left: 20px;">
			 <div class="blur-image-wrapper">
			  <canvas class="blur-image"></canvas>
			 </div>
			 <div class="transparency-sheet"></div>
			 <div class="tape-shell image-mask" data-image-repeat="true" data-mask-url="/img/ma-r90-mask.png"></div>
			 <div class="tape-gradient image-mask" data-mask-url="/img/ma-r90-mask.png"></div>
			 <div class="tab-left">
			  <div class="notch"></div>
			  <div class="ridge"></div>
			 </div>
			 <div class="tab-right">
			  <div class="notch"></div>
			  <div class="ridge"></div>
			 </div>
			 <div class="rail-left"></div>
			 <div class="rail-right"></div>
			 <div class="rail-middle">
			  <div class="rail-middle-outline">
			   <div class="tape-pad-holder">
			    <div class="tape-pad"></div>
			    <div class="tape-pad-line"></div>
			   </div>
			  </div>
			  <div class="screw-bm"></div>
			 </div>
			 <div class="screw-tl"></div>
			 <div class="screw-tr"></div>
			 <div class="screw-bl"></div>
			 <div class="screw-br"></div>
			 <div class="screw-tm"></div>
			 <div class="left reel-mask"></div>
			 <div class="right reel-mask"></div>
			 <canvas class="connecting-tape"></canvas>
			 <div class="left reel"></div>
			 <div class="left spokes"></div>
			 <div class="right reel"></div>
			 <div class="right spokes"></div>
			 <div class="progress-notches">
			  <div class="n1"></div>
			  <div class="n2"></div>
			  <div class="n3"></div>
			  <div class="n4"></div>
			  <div class="n5"></div>
			  <div class="n6"></div>
			  <div class="n7"></div>
			  <div class="n8"></div>
			  <div class="n9"></div>
			 </div>
			 <div class="label">La Boom - Selbstmord ist kein Auxweg</div>
			 <div class="aqua controls">
			  <div class="bd">
			   <ul>
			    <li><a href="#" title="play/pause" class="play">&#9658;</a></li>
			    <li><a href="#" title="rewind" class="rew">&#171;</a></li>
			    <li><a href="#" title="fast-forward" class="ffwd">&#187;</a></li>
			    <li><a href="#" title="stop" class="stop">&#9632;</a></li>
			   </ul>
			  </div>
			 </div>
			</div>
			<!-- end tape -->

			<div style="width: 100%; height: 50px;"></div>

			<!-- begin tape -->
			<div class="clear green ma-r90 cutout tape" data-url="/promotions/La_Boom_-_Burn_Engholm.mp3">
			 <div class="blur-image-wrapper">
			  <canvas class="blur-image"></canvas>
			 </div>
			 <div class="transparency-sheet"></div>
			 <div class="tape-shell image-mask" data-image-repeat="true" data-mask-url="/img/ma-r90-mask.png"></div>
			 <div class="tape-gradient image-mask" data-mask-url="/img/ma-r90-mask.png"></div>
			 <div class="tab-left">
			  <div class="notch"></div>
			  <div class="ridge"></div>
			 </div>
			 <div class="tab-right">
			  <div class="notch"></div>
			  <div class="ridge"></div>
			 </div>
			 <div class="rail-left"></div>
			 <div class="rail-right"></div>
			 <div class="rail-middle">
			  <div class="rail-middle-outline">
			   <div class="tape-pad-holder">
			    <div class="tape-pad"></div>
			    <div class="tape-pad-line"></div>
			   </div>
			  </div>
			  <div class="screw-bm"></div>
			 </div>
			 <div class="screw-tl"></div>
			 <div class="screw-tr"></div>
			 <div class="screw-bl"></div>
			 <div class="screw-br"></div>
			 <div class="screw-tm"></div>
			 <div class="left reel-mask"></div>
			 <div class="right reel-mask"></div>
			 <canvas class="connecting-tape"></canvas>
			 <div class="left reel"></div>
			 <div class="left spokes"></div>
			 <div class="right reel"></div>
			 <div class="right spokes"></div>
			 <div class="progress-notches">
			  <div class="n1"></div>
			  <div class="n2"></div>
			  <div class="n3"></div>
			  <div class="n4"></div>
			  <div class="n5"></div>
			  <div class="n6"></div>
			  <div class="n7"></div>
			  <div class="n8"></div>
			  <div class="n9"></div>
			 </div>
			 <div class="label">La Boom - Burn Engholm</div>
			 <div class="aqua controls">
			  <div class="bd">
			   <ul>
			    <li><a href="#" title="play/pause" class="play">&#9658;</a></li>
			    <li><a href="#" title="rewind" class="rew">&#171;</a></li>
			    <li><a href="#" title="fast-forward" class="ffwd">&#187;</a></li>
			    <li><a href="#" title="stop" class="stop">&#9632;</a></li>
			   </ul>
			  </div>
			 </div>
			</div>
			<!-- end tape -->


			<!-- begin tape -->
			<div class="black-micro dark clear texture tape" data-url="/promotions/La_Boom_-_Burn_Engholm.mp3" style="margin-left: 20px;">
			 <div class="rail-left"></div>
			   <div class="rail-right"></div>
			   <div class="rail-middle">
			    <div class="rail-middle-outline" style="border:none;background-color:transparent">
			     <div class="hole-1"></div>
			     <div class="hole-2"></div>
			     <div class="hole-3"></div>
			     <div class="hole-4"></div>
			     <div class="tape-pad-holder">
			      <div class="tape-pad"></div>
			      <div class="tape-pad-line"></div>
			     </div>
			    </div>
			    <div class="screw-bm"></div>
			   </div>
			   <div class="screw-tl"></div>
			   <div class="screw-tr"></div>
			   <div class="screw-bl"></div>
			   <div class="screw-br"></div>
			   <div class="screw-tm"></div>
			   <div class="left reel"></div>
			   <div class="left spokes"></div>
			   <div class="right reel"></div>
			   <div class="right spokes"></div>
			   <div class="progress-notches">
			    <div class="n1"></div>
			    <div class="n2"></div>
			    <div class="n3"></div>
			    <div class="n4"></div>
			    <div class="n5"></div>
			    <div class="n6"></div>
			    <div class="n7"></div>
			    <div class="n8"></div>
			    <div class="n9"></div>
			   </div>

			 <div class="label">La Boom - Burn Engholm</div>
			 <div class="aqua controls">
			  <div class="bd">
			   <ul>
			    <li><a href="#" title="play/pause" class="play">&#9658;</a></li>
			    <li><a href="#" title="rewind" class="rew">&#171;</a></li>
			    <li><a href="#" title="fast-forward" class="ffwd">&#187;</a></li>
			    <li><a href="#" title="stop" class="stop">&#9632;</a></li>
			   </ul>
			  </div>
			 </div>
			</div>
			<!-- end tape -->


		</div>
	</div>
</div>

<script src="/js/soundmanager2.js"></script>
<script src="/js/cassette-tape-ui.js"></script>

<?/*<script src="/js/soundmanager2.js"></script>
<script>
soundManager.setup({
  url: '/sm2/',
  flashVersion: 9, // optional: shiny features (default = 8)
  preferFlash: false,
  onready: function() {
    var mySound = soundManager.createSound({
      id: 'aSound',
      url: '/promotions/spekta_cool_air_preview.mp3'
    });
    mySound.play();
  }
});
</script>*/?>