<div class="retailerbilling">
    <div class="page">
        <div class="addresses">
            <div class="sender">3886records - Andreas Linden - Agnesstr. 3a - 53225 Bonn</div>
            <div class="recepient">
                Max Mustermann<br/>
                Musterstraße 42<br/>
                12345 Musterstadt<br/>
                Musterland
            </div>
        </div>
        
        <div class="data">
            <table border="0">
                <tr>
                    <td class="datalabel">Datum:</td>
                    <td><?= date('d.m.Y') ?></td>
                </tr>
                <tr>
                    <td class="datalabel">Unsere Ust-ID:</td>
                    <td>DE xxxxxxxx</td>
                </tr>
                <tr>
                    <td class="datalabel">Rechnungsnr.:</td>
                    <td>2014-01-1002</td>
                </tr>
             </table>
        </div>
        <div class="clear"></div>
        <div class="references">&nbsp;</div>
        <div class="clear"></div>
        <div class="content">
            <p><strong>ABRECHNUNG</strong>
            <p>
                <strong>Rechnungszeitraum: 01.01.2013 bis 31.12.2013</strong><br/>
                Eine detailierte Auflistung aller Umsätze finden Sie in der Abrechnung ab Seite 2
            </p>
            
            <table>
                <tr>
                    <th style="width: 133mm" colspan="2" class="taleft"><strong>Title</strong></th>
                    <th style="width: 21mm" class="taright">Menge</th>
                    <th style="width: 21mm" class="taright">Gesamt</th>
                </tr>
                <tr class="">
                    <td class="nobottom" colspan="2">
                        Digitale Verkäufe
                    </td>
                    <td class="taright nobottom">
                        423
                    </td>
                    <td class="taright">316,42 €</td>
                </tr>
                <tr class="last">
                    <td class="nobottom" colspan="2">
                        Online Streams
                    </td>
                    <td class="taright nobottom">
                        1027
                    </td>
                    <td class="taright">23,15 €</td>
                </tr>
                <tr class="last">
                    <td colspan="4" class="taright noborder vatop">&nbsp;</td>
                </tr>
                <tr>
                    <td colspan="3" class="taright noborder double">
                        Summe brutto:<br />
                        Ust. 19%: <br />
                        Rechnungsbetrag netto: 
                    </td>
                    <td class="taright double" style="border-bottom: 1px solid #000;">
                        339,57 €<br />
                        54,22 €<br />
                        285,35 €
                    </td>
                </tr>
                <tr class="last">
                    <td colspan="4" class="noborder">&nbsp;</td>
                </tr>
                <tr class="last">
                    <td colspan="3" style="text-align: right"><strong>Auszahlungsbetrag:</strong></td>
                    <td style="text-align: right;"><strong>0 €</strong></td>
                </tr>
                <tr class="last">
                    <td colspan="4" class="tacenter">
                        Sed nec rutrum erat. Aenean erat mauris, dignissim eu quam eget, egestas accumsan orci. Fusce sit amet leo enim. Suspendisse malesuada pellentesque eros, ut convallis eros semper placerat. Vestibulum convallis erat vel lacus rutrum pharetra. Donec rutrum tortor sit amet scelerisque hendrerit. Etiam feugiat scelerisque risus, venenatis hendrerit elit sagittis nec.
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>