<div class="container">
    <div class="jumbotron hero-unit">
        <h1>SIGNUP</h1>
        <form method="post" action="/signup" class="form-horizontal">
		  <div class="control-group form-group<?= isset($errors['user']) ? ' has-error' : '' ?>">
		    <label for="user" class="col-sm-2 control-label">Login:</label>
		    <div class="controls col-sm-10">
		      <input name="user" type="text" value="<?= @$values['user'] ?>" class="form-control" id="user" placeholder="Username">
			  <? if (isset($errors['user'])): ?>
		      	<span class="help-block"><?= $errors['user'] ?></span>
		      <? endif ?>
		    </div>
		  </div>
		  <div class="control-group form-group<?= isset($errors['code']) ? ' has-error' : '' ?>">
		    <label for="code" class="col-sm-2 control-label">Code:</label>
		    <div class="controls col-sm-10">
		      <input name="code" type="text" value="<?= @$values['code'] ?>" class="form-control" id="code" placeholder="Signup code">
			  <? if (isset($errors['code'])): ?>
		      	<span class="help-block"><?= $errors['code'] ?></span>
		      <? endif ?>
		    </div>
		  </div>
		  <div class="control-group form-group<?= isset($errors['password']) ? ' has-error' : '' ?>">
		    <label for="password" class="col-sm-2 control-label">Password:</label>
		    <div class="controls col-sm-10">
		      <input name="password" type="password" class="form-control" id="password" placeholder="Password">
		      <? if (isset($errors['password'])): ?>
		      	<span class="help-block"><?= $errors['password'] ?></span>
		      <? endif ?>
		    </div>
		  </div>
		  <div class="control-group form-group<?= isset($errors['password_conf']) ? ' has-error' : '' ?>">
		    <label for="password_conf" class="col-sm-2 control-label">Confirmation:</label>
		    <div class="controls col-sm-10">
		      <input name="password_conf" type="password" class="form-control" id="password_conf" placeholder="Password confirmation">
		      <? if (isset($errors['password_conf'])): ?>
		      	<span class="help-block"><?= $errors['password_conf'] ?></span>
		      <? endif ?>
		    </div>
		  </div>
		  <div class="control-group form-group">
		    <div class="controls col-sm-offset-2 col-sm-10">
		      <button type="submit" class="btn btn-default">Sign Up</button>
		    </div>
		  </div>
		</form>
    </div>
</div>
