<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<title></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/css/bootstrap.css" rel="stylesheet" media="screen,print">
<link href="/css/invoice.css" rel="stylesheet" media="screen,print">
</head>
<body>
<?= $content ?>
</body>
</html>
