<!DOCTYPE html>
<html lang="en" xmlns:fb="http://ogp.me/ns/fb#">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<? if (isset($metaTitle)): ?>
<title><?= $metaTitle ?> - 3886records</title>
<? else: ?>
<title>3886records - Finest Psychedelic Music</title>
<? endif ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Thirtyeight Eightysix Records is a Progressive and Psychedelic Trance label established in 2012.">
<meta name="keywords" content="3886, 3886rec., 3886rec, 3886 Records, Goa, Trance, Progressive Trance, Psychedelic Trance, Psytrance, Goatrance, Thirtyeight Eightysix, Dirty Prog, Psy Prog, Lite Prog">
<meta name="author" content="3886records">
<meta property="og:title" content="<?= isset($metaTitle) ? $metaTitle : 'Progressive & PsyTrance' ?> - 3886records" />
<? if (isset($facebookImage) && !empty($facebookImage)): ?>
<meta property="og:image" content="<?= $facebookImage ?>" />
<? endif ?>
<? if (isset($facebookDescription) && !empty($facebookDescription)): ?>
<meta property="og:description" content="<?= $facebookDescription ?>" />
<? endif ?>
<!-- the styles -->
<link href="/css/supersized.css" rel="stylesheet" media="screen">
<link rel="stylesheet" href="/theme/supersized.shutter.css" type="text/css" media="screen" />
<link href="/css/bootstrap.css" rel="stylesheet" media="screen">
<link href="/css/fonts.css" rel="stylesheet">
<link href="/css/custom.css" rel="stylesheet">
<link href="/css/bootstrap-responsive.css" rel="stylesheet">
<link href="/css/responsive.css" rel="stylesheet">
<link href="/css/font-awesome.css" rel="stylesheet">
<link href="/css/ui/jquery-ui-1.10.3.custom.css" rel="stylesheet">
<link type="text/css" href="/css/skitter.styles.css" media="all" rel="stylesheet" />
<link type="text/css" rel='stylesheet' href='/css/fullcalendar.min.css' />
<link rel="stylesheet" rel='stylesheet' href="/css/jquery-ui-timepicker-addon.css">
<link href="/css/croppic.css" rel="stylesheet">
<!--[if IE 7]>
    <link rel="stylesheet" href="/css/font-awesome-ie7.min.css">
    <![endif]-->
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
    <![endif]-->
<!-- Fav and touch icons -->
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/ico/apple-touch-icon-57-precomposed.png">
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
<script src="/js/jquery-1.9.1.js"></script>
</head>
<body class="ui">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42251912-1', '3886records.de');
  ga('send', 'pageview');
</script>
<div id="fb-root"></div>
<div class="spinner"></div> 
<div>
<header>
  <nav data-navgroup="main">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="brand" href="/" data-method="async">
            <? /*<img style=" height: 62px; margin-top: -24px; margin-right: 7px;" border="0" src="/img/3886logo-small.png" />*/ ?>
			<span class="head"><span class="raleway">3886</span>records</span>
          </a>
          <div class="nav-collapse collapse">
            <?= $navigation ?>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>
</div>
<div id="content">
    <?= $content ?>
</div>
<footer>
  <div id="controls-wrapper" class="load-item">
    <div class="container">
      <div id="controls"> 
        <div id="credits_footer"><small>3886records ©<?= date('Y') ?></div>
        <div id="social"><small> Follow us: </small>
			<a class="facebook tooltips" data-container="body" data-placement="top" data-trigger="hover" data-title="Facebook" target="_blank" href="http://www.facebook.com/3886records"><i class="icon-facebook-sign icon-large"></i></a>
			<a class="twitter tooltips" data-container="body" data-placement="top" data-trigger="hover" data-title="Twitter" target="_blank" href="http://www.twitter.com/3886records"><i class="icon-twitter-sign icon-large"></i></a>
			<a class="youtube tooltips" data-container="body" data-placement="top" data-trigger="hover" data-title="Youtube" target="_blank" href="http://www.youtube.com/user/3886records"><i class="icon-youtube-sign icon-large"></i></a>
		</div>
		<nav>
			<a data-method="async" href="/disclaimer">Imprint / Disclaimer</a>
		</nav>
    </div>
  </div>
</footer>
<script src="/js/bootstrap.min.js"></script> 
<script src="/js/jquery.easing.min.js"></script> 
<script src="/js/supersized.3.2.7.min.js"></script> 
<script src="/theme/supersized.shutter.min.js"></script> 
<script src="/js/custom.js"></script>
<script src="/js/jquery.ui.totop.min.js"></script>
<script src="/js/jquery-ui-1.10.3.custom.js"></script>
<script src="/js/jquery.animate-colors-min.js"></script>
<script src="/js/jquery.skitter.min.js"></script>
<script src='/js/moment.js'></script>
<script src='/js/fullcalendar.min.js'></script>
<script src="/js/jquery-ui-timepicker-addon.js"></script>
<script src="/js/croppic.min.js"></script>
<script>    
     jQuery(window).load(function() { 
        jQuery('.spinner').animate({'opacity':0},500,'easeOutCubic',function (){jQuery(this).css('display','none')});  
     });    
</script>
</body>
</html>
