<ul class="nav pull-right">

  <li class="dropdown"><a data-method="async" href="/pics"><span><i class="icon-film"></i></span> Gallery</b></a></li>  
  <li class="divider-vertical"></li>
  
  <li><a href="/events" data-method="async"><span><i class="icon-calendar"></i></span> Events</a></li>
  
  <li class="divider-vertical"></li>

  <li class="dropdown"><a href="/artists" class="dropdown-toggle" data-toggle="dropdown"><span class="current"><i class="icon-signal"></i></span> Releases <b class="caret"></b></a>
    <ul class="dropdown-menu">
		<li><a data-method="async" href="/releases/upcoming">Upcoming Releases</a></li>
		<li><a data-method="async" href="/releases/latest">Latest Releases</a></li>
    </ul>
  </li>

  <li class="divider-vertical"></li>

  <li class="dropdown"><a href="/artists" class="dropdown-toggle" data-toggle="dropdown"><span><i class="icon-star"></i></span> Artists <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a data-method="async" href="/artists">Artist overview</a></li>
      <li><a data-method="async" href="/artists?former=1">Former artists</a></li>
      <li class="divider"></li>
    <? foreach ($artists as $artist): ?>
    <li><a data-method="async" href="/artist/<?= $artist->key ?>" style="<?= ($artist->is_topact ? 'font-weight: bold;' : '') ?>"><?= $artist->name ?> <? if ($artist->is_topact): ?><i class="icon-star" title="Top Act" style="cursor: help;"></i><? endif ?></a></li>
    <? endforeach ?>
    </ul>
  </li>

  <li class="divider-vertical"></li>

  <li class="dropdown"><a href="/djs" class="dropdown-toggle" data-toggle="dropdown"><span><i class="icon-play-circle"></i></span> DJs <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><a data-method="async" href="/djs">DJ overview</a></li>
      <li class="divider"></li>
    <? foreach ($djs as $dj): ?>
    <li><a data-method="async" href="/dj/<?= $dj->key ?>" style="<?= ($dj->is_topact ? 'font-weight: bold;' : '') ?>"><?= $dj->name ?>  <? if ($dj->is_topact): ?><i class="icon-star" title="Top Act" style="cursor: help;"></i><? endif ?></a></li>
    <? endforeach ?>
    </ul>
  </li>
  
  <li class="divider-vertical"></li>

  <li class="dropdown"><a data-method="async" href="/genres"><span><i class="icon-music"></i></span> Genres</b></a>
    <!--<ul class="dropdown-menu">
	  <? foreach ($genres as $genre): ?>
		<li><a data-method="async" href="/genre/<?= $genre->key ?>"><?= $genre->name ?></a></li>
	  <? endforeach ?>
    </ul>
    -->
  </li>

  <li class="divider-vertical"></li>

  <? if (null === $user): ?>
    <li><a href="/login" data-method="async"><span><i class="icon-user"></i></span> Login</a></li>
  <? else: ?>
    <li class="dropdown"><a href="/profile" class="dropdown-toggle" data-toggle="dropdown"><span><i class="icon-user"></i></span> Account <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a data-method="async" href="/profile">Overview</a></li>
        <? if ($user->artist_id): ?>
        	<li><a data-method="async" href="/profile/edit">Edit Profile</a></li>
        <? endif ?>
        <li><a data-method="async" href="/event/add">Add Event</a></li>
        <? if ($user->rights & \Models\User::RIGHT_SIGNUPCODES): ?>
          <li><a data-method="async" href="/profile/signupcodes">Signup Codes</a></li>
        <? endif ?>
        <? if ($user->rights & \Models\User::RIGHT_BOOKINGMANAGER): ?>
          <li><a data-method="async" href="/bookingmanager">Booking Management</a></li>
        <? endif ?>
        <li><a href="/logout">Logout</a></li>
      </ul>
    </li>
  <? endif ?>

  <?/*
  <li class="divider-vertical"></li>
  <li class="dropdown"><a href="/artists" class="dropdown-toggle" data-toggle="dropdown"><span class="current"><i class="icon-headphones"></i></span> Labels <b class="caret"></b></a>
    <ul class="dropdown-menu">
	  <? foreach ($labels as $label): ?>
		<li><a data-method="async" href="/label/<?= $label->key ?>"><?= $label->name ?></a></li>
	  <? endforeach ?>
    </ul>
  </li>
  */?>

</ul>
