<? $page = 0 ?>
<? ob_start() ?>
<div class="header">
            <img src="/img/logo-oneliner-black-small.png"><br>
            <div class="sender">
                Andreas Linden&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;Agnesstr. 3A&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;53225 Bonn&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;Deutschland<br>
                Tel. +49-(0)178/7108481&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;E-Mail: info@3886records.de
            </div>
        </div>
        
        <div class="addresses">
            <div class="recepient">
                <strong><?= $report->artist->name ?></strong><br>
                <?= $report->artist->firstname ?> <?= $report->artist->lastname ?><br>
                <?= $report->artist->street ?><br>
                <?= $report->artist->zip ?> <?= $report->artist->city ?><br>
                <?= $report->artist->country ?>
            </div>
        </div>
        
        <div class="data">
            <table border="0">
                <tr>
                    <td class="datalabel">Datum:</td>
                    <td><?= $report->date ?></td>
                </tr>
                <tr>
                    <td class="datalabel">Kundennummer:</td>
                    <td><?= $report->customerNumber ?></td>
                </tr>
                <tr>
                    <td class="datalabel">Rechnungsnr.:</td>
                    <td><?= $report->invoiceNumber ?></td>
                </tr>
             </table>
        </div>
<? $pageHeader = ob_get_clean(); ?>

<div class="invoice">
    <page size="A4" class="page">
        <?= $pageHeader ?>
        <div class="clear"></div>
        <div class="references">&nbsp;</div>
        <div class="clear"></div>
        <div class="content">
            <h2>ABRECHNUNG</h2>
            <p>
                Für den Abrechnungszeitraum von <?= $report->quarterFrom ?> bis <?= $report->quarterTo ?></strong><br/>
                Eine detailierte Auflistung aller Umsätze finden Sie ab Seite 2.
            </p>
            
            <table>
                <tr>
                    <th colspan="2" class="taleft"><strong>Title</strong></th>
                    <th style="width: 25mm" class="taright">Menge</th>
                    <th style="width: 25mm" class="taright">Gesamt</th>
                </tr>
                <? $numItems = count($report->items) ?>
                <? $sum = 0 ?>
                <? for ($n = 0; $n < $numItems; $n++): ?>
                    <? $sum += round($report->items[$n]->value, 2) ?>
                    <tr class="<?= $n == $numItems - 1 ? 'last' : '' ?>">
                        <td class="nobottom" colspan="2">
                            <?= $report->items[$n]->position ?>
                        </td>
                        <td class="taright nobottom">
                            <?= $report->items[$n]->num ?>
                        </td>
                        <td class="taright">
                            <?= sprintf("%.2f", round($report->items[$n]->value, 2)) ?> GBP
                        </td>
                    </tr>
                <? endfor ?>
                <tr class="last">
                    <td colspan="4" class="taright noborder vatop">&nbsp;</td>
                </tr>
                <tr>
                    <td colspan="3" class="taright noborder double">
                        <strong>Summe:</strong>
                        <!--Summe brutto:<br />
                        Ust. 19%: <br />
                        Rechnungsbetrag netto: -->
                    </td>
                    <td class="taright double" style="border-bottom: 1px solid #000;">
                        <strong><?= sprintf("%.2f", round($sum, 2)) ?> GBP</strong>
                        <!--0 GBP<br />
                        0 GBP<br />
                        0 GBP-->
                    </td>
                </tr>
                <tr class="last">
                    <td colspan="4" class="noborder">&nbsp;</td>
                </tr>
                <tr class="last">
                    <td colspan="3" style="text-align: right"><strong>Auszahlungsbetrag:</strong></td>
                    <td style="text-align: right;"><strong>0.00 GBP</strong></td>
                </tr>
                <tr class="last">
                    <td colspan="4" class="tacenter">
                        Es wird gemäß §19 Abs. 1 Umsatzsteuergesetz keine Umsatzsteuer ausgeschrieben. Eine Auszahlung ist ab dem vertraglich festgelegten Betrag möglich. Wurde keine Auszahlungsgrenze definiert, liegt diese bei 50.00 GPB.
                    </td>
                </tr>
            </table>
        </div>
        <div class="footer">
            <table>
                <tr>
                    <td>
                        <strong>Anschrift</strong><br>
                        Fa. Andreas Linden<br>
                        Agnesstr. 3a<br>
                        53225 Bonn
                    </td>
                    <td>
                        <strong>Bankverbindung</strong><br>
                        Andreas Linden<br>
                        IBAN: DE55 3806 0186 0803 7220 13<br>
                        BIC: GENODED1BRS
                    </td>
                    <td>
                        <strong>Geschäftsführung</strong><br>
                        Andreas Linden<br>
                        Steuernummer 1234567890<br>
                        Finanzamt Bonn-Außenstadt
                    </td>
                    <td class="vabottom">Seite <?= ++$page ?></td>
                </tr>
            </table>
        </div>
    </page>
    <? if (count($details)): ?>

				<? $sumDetail = 0 ?>
                <? $numItems = count($details) ?>
                <? for ($n = 0; $n < $numItems; $n++): ?>
                    <? if ($n % 35 === 0): ?>
                        <? if ($n !== 0): ?>
                                        <tr>
                                            <td colspan="5" class="taright noborder double">
                                                <strong>Zwischensumme:</strong>
                                            </td>
                                            <td class="taright double" style="border-bottom: 1px solid #000;">
                                                <strong><?= $sumDetail ?> GBP</strong>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="footer">
                                    <table>
                                        <tr>
                                            <td>
                                                <strong>Anschrift</strong><br>
                                                Fa. Andreas Linden<br>
                                                Agnesstr. 3a<br>
                                                53225 Bonn
                                            </td>
                                            <td>
                                                <strong>Bankverbindung</strong><br>
                                                Andreas Linden<br>
                                                IBAN: DE55 3806 0186 0803 7220 13<br>
                                                BIC: GENODED1BRS
                                            </td>
                                            <td>
                                                <strong>Geschäftsführung</strong><br>
                                                Andreas Linden<br>
                                                Steuernummer 1234567890<br>
                                                Finanzamt Bonn-Außenstadt
                                            </td>
                                            <td class="vabottom">Seite <?= ++$page ?></td>
                                        </tr>
                                    </table>
                                </div>
                            </page>
                        <? endif ?>
                             <page size="A4" class="page details">
                                <?= $pageHeader ?>
                                <div class="clear"></div>
                                <div class="content">
                                    <? if ($n === 0): ?>
                                        <h2>DETAILLIERTE UMSATZAUFLISTUNG</h2>
                                    <? else: ?>
                                        <h2>FORTSETZUNG DER UMSATZAUFLISTUNG</h2>
                                    <? endif ?>
                                    <table>
                                        <tr>
                                            <th style="width: 32mm;" class="taleft"><strong>Artist</strong></th>
                                            <th class="taleft"><strong>Track/Release</strong></th>
                                            <th style="width: 27mm;" class="taleft"><strong>Format</strong></th>
                                            <th style="width: 20mm;"class="taleft"><strong>Store</strong></th>
                                            <th style="width: 10mm;" class="taright"><strong>Num</strong></th>
                                            <th style="width: 32mm;"class="taright"><strong>Value</strong></th>
                                        </tr>
                    <? elseif ($n % 10 === 0): ?>
                        </table>
                        <table>
                    <? endif ?>
                    <? $sumDetail += $details[$n]->avail ?>
					<tr class="<?= $n == $numItems - 1 ? 'last' : '' ?>">
                        <td style="width: 32mm;" class="nobottom">
                            <?= $details[$n]->release_artist ?>
                        </td>
                        <td class="nobottom">
                            <? if ($details[$n]->sale_type == 'Track'): ?>
                                <?= $details[$n]->track_title ?> (Track)
                            <? else: ?>
                                <?= $details[$n]->release_name ?> (Release)
                            <? endif ?>
                            
                        </td>
                        <td style="width: 27mm;" class="nobottom">
                            <?= $details[$n]->format ?>
                        </td>
                        <td style="width: 20mm;" width="" class="nobottom">
                            <?= $details[$n]->store ?>
                        </td>
                        <td  style="width: 10mm;" class="nobottom taright">
                            <?= $details[$n]->quantity ?>
                        </td>
                        <td style="width: 32mm;" class="nobottom taright">
                            <nobr><?= $details[$n]->avail ?> GBP</nobr>
                        </td>
                    </tr>
                <? endfor ?>
                <tr>
                    <td colspan="5" class="taright noborder double">
                        <strong>Summe:</strong>
                        <!--Summe brutto:<br />
                        Ust. 19%: <br />
                        Rechnungsbetrag netto: -->
                    </td>
                    <td class="taright double" style="border-bottom: 1px solid #000;">
                        <strong><?= $sumDetail ?> GBP</strong>
                        <!--0 GBP<br />
                        0 GBP<br />
                        0 GBP-->
                    </td>
                </tr>
                <tr class="last">
                    <td colspan="6" class="noborder">&nbsp;</td>
                </tr>
                <tr class="last">
                    <td colspan="6" class="tacenter">
                        Unsere Digital Service Provider haben unterschiedliche Abrechnungszeiträume. Daher kann es vorkommen, dass Umsätze nicht in dieser Rechnung aufgeführt sind auch wenn Sie innerhalb der einbezogenen Quartale stattgefunden haben. Spätestens ein Quartal nach der Abrechnung mit unseren Digital Service Providern werden die Umsätze hier aufgeführt.
                    </td>
                </tr>
            </table>
        </div>
        <div class="footer">
            <table>
                <tr>
                    <td>
                        <strong>Anschrift</strong><br>
                        Fa. Andreas Linden<br>
                        Agnesstr. 3a<br>
                        53225 Bonn
                    </td>
                    <td>
                        <strong>Bankverbindung</strong><br>
                        Andreas Linden<br>
                        IBAN: DE55 3806 0186 0803 7220 13<br>
                        BIC: GENODED1BRS
                    </td>
                    <td>
                        <strong>Geschäftsführung</strong><br>
                        Andreas Linden<br>
                        Steuernummer 1234567890<br>
                        Finanzamt Bonn-Außenstadt
                    </td>
                    <td class="vabottom">Seite <?= ++$page ?></td>
                </tr>
            </table>
        </div>
</page>
<? endif ?>

