<?= ViewLoader::load('breadcrumb', array('items' => $breadcrumb)) ?>
<div class="container">
    <? if (isset($artists) && count($artists)): ?>
	<div class="jumbotron hero-unit">
		<div>
            <h1>Signup Codes</h1>
        </div>
		<p>
			<? foreach ($artists as $artist): ?>
				<span style="font-weight: bold;<?= ($artist->codeUsed ? 'color: #00ff00;' : '') ?>"><?= $artist->name ?></span>: <?= $artist->code ?> <a href="https://www.3886records.de/signup?ref=<?= base64_encode($artist->id.'x') ?>">https://www.3886records.de/signup?ref=<?= base64_encode($artist->id.'x') ?></a><br>
			<? endforeach ?>
		</p>
	</div>
	<? endif ?>
</div>